class CBlock
//	SFAddress	author;
//	SFString	difficulty;
//	SFString	extraData;
//	SFString	gasLimit;
//	SFString	gasUsed;
//	SFHash		hash;
	SFString	logsBloom;
//	SFHash		mixHash;
	SFAddress	miner;
//	SFString	nonce;
	SFString	number;
//	SFHash		parentHash;
//	SFString	receiptRoot;
//a	SFString	receiptsRoot;
//	SFStringArray	sealFields;
//	SFString	sha3Uncles;
	SFString	size;
//	SFString	stateRoot;
	SFString	timestamp;
//	SFString	totalDifficulty;
	CTransactionArray transactions;
//p		SFHash blockHash;
//p		SFInt32 blockNumber;
//		SFString creates;
//		SFInt32 confirmations;
		SFAddress contractAddress;
//r		SFString cumulativeGasUsed;
		SFAddress from;
		SFInt32 gas;
		SFString gasPrice;
//r		SFString gasUsed;
//		SFHash hash;
		SFString input;
		SFBool isError;
		SFBool isInternalTx;
		SFInt32 nonce;
//		SFHash r;
//		SFString raw;
//		SFHash s;
//p		SFInt32 timeStamp;
		SFAddress to;
		SFInt32 transactionIndex;
//		SFHash v;
		SFString value;
		CReceipt receipt;
//p			SFHash blockHash;
//p			SFInt32 blockNumber;
//p			SFAddress contractAddress;
			SFInt32 cumulativeGasUsed;
//p			SFAddress from;
			SFInt32 gasUsed;
			CLogEntryArray logs;
				SFAddress address;
//p				SFHash blockHash;
//p				SFInt32 blockNumber;
				SFString data;
				SFInt32 logIndex;
				SFStringArray topics;
//p				SFHash transactionHash;
//p				SFInt32 transactionIndex;
			SFString logsBloom;
//			SFString root;
			SFAddress to;
//			SFHash transactionHash;
//p			SFInt32 transactionIndex;
		CTrace trace;
			SFInt32 gas;
			SFString returnValue;
			CStructLogArray structLogs;
				SFInt32 depth;
				SFBool error;
				SFInt32 gas;
				SFInt32 gasCost;
				SFStringArray memory;
				SFString op;
				SFInt32 pc;
				SFStringArray stack;
				SFStringArray storage;
//	SFString transactionsRoot;
//	SFStringArray uncles;
